#!/usr/bin/env python
from __future__ import (unicode_literals, absolute_import,
                        print_function, division)
import argparse
import sys
import json
import re
import base64
import calendar
import csv
import datetime
import hashlib
import glob
import itertools
import json
import math
import os
import random
import re
import shutil
import tempfile
from collections import Counter
from collections import OrderedDict
from itertools import groupby
from uuid import uuid4

#if args.pre_cmd:
    #exec(args.pre_cmd)

#if args.post_cmd:
    #exec(args.post_cmd)

import rlcompleter


def complete_all(c, s, idx):
    global x
    global l
    x = str()
    l = list()
    if c.complete(s, idx):
        return [c.complete(s, idx)] + complete_all(c, s, idx + 1)
    return []


def parse_string(prefix, raw_input):
    if prefix == '':
        return ['sys', 'json', 're', 'base64', 'calendar', 'csv', 'datetime', 'hashlib', 'itertools', 'json', 'math', 'os', 'random', 're', 'shutil']
    elif prefix.startswith('--') and not any(q in raw_input for q in ["'", '"']):
        return ['--si', '--so', '--ji', '--jo', '--i']
    elif prefix.startswith('-') and not any(q in raw_input for q in ["'", '"']):
        return ['-h', '-x', '-fx', '-l', '-c', '-C']
    c = rlcompleter.Completer()
    options = list(set(complete_all(c, prefix, 0)))
    if prefix.endswith('.'):
        options = [x for x in options if '_' not in x]
    return options



def parse_input(raw_input):
    input = raw_input.rstrip().split(' ')[-1]
    if len(input) > 0 and input[0] in ['"', "'"]:
        input = input[1:]
    return input


def main():
    raw_input = next(sys.stdin)
    prefix = parse_input(raw_input)
    options = parse_string(prefix, raw_input)

    with open('/tmp/a.txt', 'w') as f:
        f.write(raw_input + '\n')
        f.write(prefix + '\n')
        for x in options:
            f.write(x + '\n')
    if len(options) <= 1:
        options = options + [x + "'" for x in options]
    print(' '.join(options))

if __name__ == '__main__':
    main()
